version: "3.8"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - awssample-network
    depends_on:
      - awssample-api
        # condition: service_healthy

  awssample-api:
    image: awssample-api
    container_name: awssample-api
    hostname: awssample-api
    volumes:
      - awssample_api:/data/api
    build:
      context: .
      dockerfile: AwsApiSample.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080"
    networks:
      - awssample-network
    # healthcheck:
    #   test: wget --no-verbose --tries=1 --spider http://localhost:8080/healthz || exit 1
    #   interval: 30s
    #   retries: 5
    #   start_period: 20s
    #   timeout: 10s

volumes:
  awssample_api:
    driver: local

networks:
  awssample-network:
    name: awssample-network
    driver: bridge
